/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.main;

import develop.EmailTest;
import ini.RMExportDBSpecFolder;
import ini.RMTestIniFileHandler;
import java.io.File;
import passwordconvert.PasswordConvertQueryHandler;
import passwordconvert.PasswordQuerySQL;
import rcommon.database.rsqlbase.RY_OprSimple;
import rcommon.fileIO.txt.RIniFile2;
import readingminstest.RM_AppInitTest;
import rswin.ui.file.RSwinFileSelect;
import rytable.RY_DataBaseExcelExport;
import rytable.RY_TableManager;
import test.database.RMResetDataBaseModule;
import ui.database.DBSchemaChangeDlg;
import ui.database.DBScriptDlg;

/**
 *
 * @author renhongxiang
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        loadIni();
    }

    public static void loadIni(){
        
        RMTestIniFileHandler iniHandler = new RMTestIniFileHandler();
        iniHandler.BuildInitHandle();
        RIniFile2 inifile = new RIniFile2();        
        inifile.setIniHandler(iniHandler);
        inifile.doLoadIniAuto();
        
    }
    
    public static void saveIni(){
        RMTestIniFileHandler iniHandler = new RMTestIniFileHandler();
        iniHandler.BuildInitHandle();
        RIniFile2 inifile = new RIniFile2();        
        inifile.setIniHandler(iniHandler);
        inifile.doSaveIniAuto();        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem_DB_Spec = new javax.swing.JMenuItem();
        jMenuItem_DB_Script = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenu_ResetDB = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jMenu1.setText("DataBase");

        jMenuItem_DB_Spec.setText("Export Database Specification");
        jMenuItem_DB_Spec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_DB_SpecActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem_DB_Spec);

        jMenuItem_DB_Script.setText("Database Script");
        jMenuItem_DB_Script.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_DB_ScriptActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem_DB_Script);

        jMenuItem5.setText("DataBase Modify Script");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem5);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Develop Tool");

        jMenuItem1.setText("Convert Password Encrypt");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuItem2.setText("Test_Email");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Testing");

        jMenu_ResetDB.setText("ResetDataBase");
        jMenu_ResetDB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu_ResetDBActionPerformed(evt);
            }
        });
        jMenu3.add(jMenu_ResetDB);

        jMenuItem3.setText("Register User");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem3);

        jMenuItem4.setText("Login User");
        jMenu3.add(jMenuItem4);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 579, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 356, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem_DB_SpecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_DB_SpecActionPerformed
        // TODO add your handling code here:
        RMExportDBSpecFolder specFolder = new RMExportDBSpecFolder();
        File selectFile = RSwinFileSelect.doSelectSaveFile(this, specFolder);
        if(selectFile != null){
            RY_DataBaseExcelExport export = new RY_DataBaseExcelExport();
            if(export != null){
                RM_AppInitTest ini = new RM_AppInitTest();
                RY_TableManager db = ini.getTableManager();
                if(db!=null){
                    export.setDataBase(db);
                    export.exportSpec(selectFile);
                }
            }
        }                
        
    }//GEN-LAST:event_jMenuItem_DB_SpecActionPerformed

    private void jMenuItem_DB_ScriptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_DB_ScriptActionPerformed
        // TODO add your handling code here:
        DBScriptDlg dlg = new DBScriptDlg(this, true);
        dlg.setVisible(true);
        
    }//GEN-LAST:event_jMenuItem_DB_ScriptActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        PasswordQuerySQL sql = new PasswordQuerySQL();
        PasswordConvertQueryHandler handler = new PasswordConvertQueryHandler();
        sql.setQueryHandler(handler);
        RY_OprSimple.DoQuery(sql);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        EmailTest test = new EmailTest();
        test.doEmailTest();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenu_ResetDBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu_ResetDBActionPerformed
        // TODO add your handling code here:
        RMResetDataBaseModule module = new RMResetDataBaseModule();
        module.buildModule();
        module.RunTest();
    }//GEN-LAST:event_jMenu_ResetDBActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        saveIni();
    }//GEN-LAST:event_formWindowClosing

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
        DBSchemaChangeDlg dlg = new DBSchemaChangeDlg(this, true);
        dlg.setVisible(true);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem_DB_Script;
    private javax.swing.JMenuItem jMenuItem_DB_Spec;
    private javax.swing.JMenuItem jMenu_ResetDB;
    // End of variables declaration//GEN-END:variables
}
